ALTER TABLE configuraciones DROP FOREIGN KEY configuraciones_ibfk_1;
ALTER TABLE sesiones DROP FOREIGN KEY sesiones_ibfk_1;
ALTER TABLE logs DROP FOREIGN KEY logs_ibfk_1;
ALTER TABLE logs DROP FOREIGN KEY logs_ibfk_2;
ALTER TABLE amigos DROP FOREIGN KEY amigos_ibfk_1;
ALTER TABLE amigos DROP FOREIGN KEY amigos_ibfk_2;
ALTER TABLE multimedia DROP FOREIGN KEY multimedia_ibfk_1;
ALTER TABLE servidores DROP FOREIGN KEY servidores_ibfk_1;
ALTER TABLE servidores DROP FOREIGN KEY servidores_ibfk_2;
ALTER TABLE usuarios_servidores DROP FOREIGN KEY usuarios_servidores_ibfk_1;
ALTER TABLE usuarios_servidores DROP FOREIGN KEY usuarios_servidores_ibfk_2;
ALTER TABLE mensajes DROP FOREIGN KEY mensajes_ibfk_1;
ALTER TABLE mensajes DROP FOREIGN KEY mensajes_ibfk_2;
ALTER TABLE reacciones_mensajes DROP FOREIGN KEY reacciones_mensajes_ibfk_1;
ALTER TABLE reacciones_mensajes DROP FOREIGN KEY reacciones_mensajes_ibfk_2;
ALTER TABLE reportes DROP FOREIGN KEY reportes_ibfk_1;
ALTER TABLE reportes DROP FOREIGN KEY reportes_ibfk_2;
ALTER TABLE usuarios DROP FOREIGN KEY usuarios_ibfk_1;

DROP TABLE IF EXISTS reacciones_mensajes;
DROP TABLE IF EXISTS mensajes;
DROP TABLE IF EXISTS usuarios_servidores;
DROP TABLE IF EXISTS servidores;
DROP TABLE IF EXISTS multimedia;
DROP TABLE IF EXISTS amigos;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS sesiones;
DROP TABLE IF EXISTS configuraciones;
DROP TABLE IF EXISTS reportes;
DROP TABLE IF EXISTS usuarios;